# Generated by Django 3.1.1 on 2020-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('acceleration', models.IntegerField(default=0)),
                ('altitude', models.IntegerField(default=0)),
            ],
        ),
    ]
