# Generated by Django 3.0.1 on 2020-08-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Data',
        ),
    ]
