# Generated by Django 3.1.1 on 2020-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0002_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('acceleration', models.IntegerField(default=0)),
                ('altitude', models.IntegerField(default=0)),
            ],
        ),
    ]
