# Generated by Django 3.1.1 on 2020-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0002_elevator_pir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
