# Generated by Django 3.1.1 on 2020-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0003_elevator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='number',
            field=models.IntegerField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
