# Generated by Django 3.1.1 on 2020-10-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0004_auto_20201030_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AlterField(
            model_name='elevator',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
