# Generated by Django 3.1.1 on 2020-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0005_auto_20201109_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission_number',
            field=models.IntegerField(auto_created=True, serialize=False),
        ),
    ]
