# Generated by Django 3.1.1 on 2020-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0006_auto_20201111_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='base_altitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='current_altitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission_number',
            field=models.IntegerField(default=0),
        ),
    ]
