# Generated by Django 3.1.1 on 2020-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0008_remove_elevator_altitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator',
            old_name='acceleration',
            new_name='ir',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='pir',
        ),
        migrations.AddField(
            model_name='elevator',
            name='acceleration_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='acceleration_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='acceleration_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='pitch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='roll',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='elevator',
            name='yaw',
            field=models.FloatField(default=0.0),
        ),
    ]
