# Generated by Django 3.1.1 on 2020-11-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_api', '0009_auto_20201118_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='elevator',
            name='temperature',
        ),
    ]
